#![allow(non_camel_case_types)]

pub mod global {
    mod account_level_excel_generated;
    mod account_state_generated;
    mod anniversary_generated;
    mod assist_echelon_type_convert_excel_generated;
    mod attendance_count_rule_generated;
    mod attendance_excel_generated;
    mod attendance_reset_type_generated;
    mod attendance_reward_excel_generated;
    mod attendance_type_generated;
    mod bgm_global_excel_generated;
    mod bgmexcel_generated;
    mod bgmraid_excel_generated;
    mod bgmuiexcel_generated;
    mod camera_excel_generated;
    mod character_dialog_emoji_excel_generated;
    mod character_dialog_event_excel_generated;
    mod character_dialog_excel_generated;
    mod character_dialog_subtitle_excel_generated;
    mod character_gear_excel_generated;
    mod character_gear_level_excel_generated;
    mod character_potential_excel_generated;
    mod character_potential_reward_excel_generated;
    mod character_potential_stat_excel_generated;
    mod character_voice_excel_generated;
    mod character_voice_subtitle_excel_generated;
    mod clan_assist_slot_excel_generated;
    mod clan_chatting_emoji_excel_generated;
    mod clan_reward_excel_generated;
    mod clan_reward_type_generated;
    mod club_generated;
    mod collection_unlock_type_generated;
    mod combat_emoji_excel_generated;
    mod content_enter_cost_reduce_excel_generated;
    mod content_spoiler_popup_excel_generated;
    mod content_type_generated;
    mod contents_scenario_excel_generated;
    mod contents_shortcut_excel_generated;
    mod currency_additional_charge_type_generated;
    mod currency_excel_generated;
    mod currency_over_charge_type_generated;
    mod currency_types_generated;
    mod cvcollection_type_generated;
    mod cvprint_type_generated;
    mod cvunlock_scenario_type_generated;
    mod daily_refill_type_generated;
    mod dialog_category_generated;
    mod dialog_condition_detail_generated;
    mod dialog_condition_generated;
    mod dialog_type_generated;
    mod dream_maker_ending_condition_generated;
    mod dream_maker_ending_reward_type_generated;
    mod dream_maker_ending_type_generated;
    mod dream_maker_multiplier_condition_generated;
    mod dream_maker_param_operation_type_generated;
    mod dream_maker_parameter_type_generated;
    mod dream_maker_result_generated;
    mod echelon_extension_type_generated;
    mod echelon_type_generated;
    mod emoji_event_generated;
    mod equipment_option_type_generated;
    mod event_content_notify_excel_generated;
    mod event_content_spoiler_popup_excel_generated;
    mod event_content_treasure_cell_reward_excel_generated;
    mod event_content_treasure_excel_generated;
    mod event_content_treasure_reward_excel_generated;
    mod event_content_treasure_round_excel_generated;
    mod event_content_type_generated;
    mod event_notify_type_generated;
    mod event_target_type_generated;
    mod farming_dungeon_location_manage_excel_generated;
    mod favor_level_excel_generated;
    mod favor_level_reward_excel_generated;
    mod fixed_echelon_setting_excel_generated;
    mod form_generated;
    mod formation_location_excel_generated;
    mod get_sticker_condition_type_generated;
    mod ground_module_reward_excel_generated;
    mod id_card_background_excel_generated;
    mod information_excel_generated;
    mod loading_image_excel_generated;
    mod localize_char_profile_change_excel_generated;
    mod localize_error_excel_generated;
    mod localize_etc_excel_generated;
    mod localize_excel_generated;
    mod localize_skill_excel_generated;
    mod mail_type_generated;
    mod memory_lobby_category_generated;
    mod memory_lobby_excel_generated;
    mod memory_lobby_global_excel_generated;
    mod message_popup_button_type_generated;
    mod message_popup_excel_generated;
    mod message_popup_image_position_type_generated;
    mod message_popup_layout_generated;
    mod mini_game_defense_character_ban_excel_generated;
    mod mini_game_defense_fixed_stat_excel_generated;
    mod mini_game_defense_info_excel_generated;
    mod mini_game_defense_stage_excel_generated;
    mod mini_game_dream_collection_scenario_excel_generated;
    mod mini_game_dream_daily_point_excel_generated;
    mod mini_game_dream_ending_excel_generated;
    mod mini_game_dream_ending_reward_excel_generated;
    mod mini_game_dream_info_excel_generated;
    mod mini_game_dream_parameter_excel_generated;
    mod mini_game_dream_replay_scenario_excel_generated;
    mod mini_game_dream_schedule_excel_generated;
    mod mini_game_dream_schedule_result_excel_generated;
    mod mini_game_dream_timeline_excel_generated;
    mod mini_game_road_puzzle_info_excel_generated;
    mod mini_game_road_puzzle_map_excel_generated;
    mod mini_game_road_puzzle_rail_set_reward_excel_generated;
    mod mini_game_road_puzzle_reward_excel_generated;
    mod mini_game_road_puzzle_voice_excel_generated;
    mod mission_emergency_complete_excel_generated;
    mod motion_generated;
    mod move_end_generated;
    mod multi_floor_raid_reward_excel_generated;
    mod multi_floor_raid_season_manage_excel_generated;
    mod multi_floor_raid_stage_excel_generated;
    mod multi_floor_raid_stat_change_excel_generated;
    mod multiple_condition_check_type_generated;
    mod nation_generated;
    mod obstacle_stat_excel_generated;
    mod open_condition_content_generated;
    mod open_condition_excel_generated;
    mod operator_condition_generated;
    mod operator_excel_generated;
    mod parcel_type_generated;
    mod position_generated;
    mod potential_stat_bonus_rate_type_generated;
    mod production_step_generated;
    mod rarity_generated;
    mod reward_tag_generated;
    mod road_puzzle_voice_condition_generated;
    mod scenario_bgeffect_excel_generated;
    mod scenario_bgname_excel_generated;
    mod scenario_bgname_global_excel_generated;
    mod scenario_bgscroll_generated;
    mod scenario_bgtype_generated;
    mod scenario_character_emotion_excel_generated;
    mod scenario_character_name_excel_generated;
    mod scenario_character_shapes_generated;
    mod scenario_character_situation_set_excel_generated;
    mod scenario_content_collection_excel_generated;
    mod scenario_content_type_generated;
    mod scenario_effect_excel_generated;
    mod scenario_mode_excel_generated;
    mod scenario_mode_reward_excel_generated;
    mod scenario_mode_sub_types_generated;
    mod scenario_mode_types_generated;
    mod scenario_resource_info_excel_generated;
    mod scenario_script_excel_generated;
    mod scenario_transition_excel_generated;
    mod school_dungeon_reward_excel_generated;
    mod school_dungeon_stage_excel_generated;
    mod school_dungeon_type_generated;
    mod service_action_excel_generated;
    mod service_action_type_generated;
    mod shortcut_content_type_generated;
    mod shortcut_type_excel_generated;
    mod skill_additional_tooltip_excel_generated;
    mod sound_uiexcel_generated;
    mod spine_lipsync_excel_generated;
    mod stage_difficulty_generated;
    mod stage_file_refresh_setting_excel_generated;
    mod stage_topography_generated;
    mod star_goal_type_generated;
    mod stat_level_interpolation_excel_generated;
    mod stat_level_up_type_generated;
    mod stat_type_generated;
    mod sticker_check_pass_type_generated;
    mod sticker_get_condition_type_generated;
    mod sticker_group_excel_generated;
    mod sticker_page_content_excel_generated;
    mod story_strategy_excel_generated;
    mod strategy_environment_generated;
    mod tag_generated;
    mod toast_excel_generated;
    mod toast_type_generated;
    mod tutorial_character_dialog_excel_generated;
    mod tutorial_excel_generated;
    mod tutorial_failure_content_type_generated;
    mod tutorial_failure_image_excel_generated;
    mod under_cover_stage_excel_generated;
    mod video_excel_generated;
    mod video_global_excel_generated;
    mod voice_common_excel_generated;
    mod voice_event_generated;
    mod voice_excel_generated;
    mod voice_logic_effect_excel_generated;
    mod voice_room_exception_excel_generated;
    mod voice_spine_excel_generated;
    mod voice_timeline_excel_generated;
    mod web_apierror_level_generated;
    mod week_day_generated;
    mod week_dungeon_type_generated;
    mod world_raid_condition_excel_generated;

    pub use self::account_level_excel_generated::AccountLevelExcel;
    pub use self::account_state_generated::AccountState;
    pub use self::anniversary_generated::Anniversary;
    pub use self::assist_echelon_type_convert_excel_generated::AssistEchelonTypeConvertExcel;
    pub use self::attendance_count_rule_generated::AttendanceCountRule;
    pub use self::attendance_excel_generated::AttendanceExcel;
    pub use self::attendance_reset_type_generated::AttendanceResetType;
    pub use self::attendance_reward_excel_generated::AttendanceRewardExcel;
    pub use self::attendance_type_generated::AttendanceType;
    pub use self::bgm_global_excel_generated::BGM_GlobalExcel;
    pub use self::bgmexcel_generated::BGMExcel;
    pub use self::bgmraid_excel_generated::BGMRaidExcel;
    pub use self::bgmuiexcel_generated::BGMUIExcel;
    pub use self::camera_excel_generated::CameraExcel;
    pub use self::character_dialog_emoji_excel_generated::CharacterDialogEmojiExcel;
    pub use self::character_dialog_event_excel_generated::CharacterDialogEventExcel;
    pub use self::character_dialog_excel_generated::CharacterDialogExcel;
    pub use self::character_dialog_subtitle_excel_generated::CharacterDialogSubtitleExcel;
    pub use self::character_gear_excel_generated::CharacterGearExcel;
    pub use self::character_gear_level_excel_generated::CharacterGearLevelExcel;
    pub use self::character_potential_excel_generated::CharacterPotentialExcel;
    pub use self::character_potential_reward_excel_generated::CharacterPotentialRewardExcel;
    pub use self::character_potential_stat_excel_generated::CharacterPotentialStatExcel;
    pub use self::character_voice_excel_generated::CharacterVoiceExcel;
    pub use self::character_voice_subtitle_excel_generated::CharacterVoiceSubtitleExcel;
    pub use self::clan_assist_slot_excel_generated::ClanAssistSlotExcel;
    pub use self::clan_chatting_emoji_excel_generated::ClanChattingEmojiExcel;
    pub use self::clan_reward_excel_generated::ClanRewardExcel;
    pub use self::clan_reward_type_generated::ClanRewardType;
    pub use self::club_generated::Club;
    pub use self::collection_unlock_type_generated::CollectionUnlockType;
    pub use self::combat_emoji_excel_generated::CombatEmojiExcel;
    pub use self::content_enter_cost_reduce_excel_generated::ContentEnterCostReduceExcel;
    pub use self::content_spoiler_popup_excel_generated::ContentSpoilerPopupExcel;
    pub use self::content_type_generated::ContentType;
    pub use self::contents_scenario_excel_generated::ContentsScenarioExcel;
    pub use self::contents_shortcut_excel_generated::ContentsShortcutExcel;
    pub use self::currency_additional_charge_type_generated::CurrencyAdditionalChargeType;
    pub use self::currency_excel_generated::CurrencyExcel;
    pub use self::currency_over_charge_type_generated::CurrencyOverChargeType;
    pub use self::currency_types_generated::CurrencyTypes;
    pub use self::cvcollection_type_generated::CVCollectionType;
    pub use self::cvprint_type_generated::CVPrintType;
    pub use self::cvunlock_scenario_type_generated::CVUnlockScenarioType;
    pub use self::daily_refill_type_generated::DailyRefillType;
    pub use self::dialog_category_generated::DialogCategory;
    pub use self::dialog_condition_detail_generated::DialogConditionDetail;
    pub use self::dialog_condition_generated::DialogCondition;
    pub use self::dialog_type_generated::DialogType;
    pub use self::dream_maker_ending_condition_generated::DreamMakerEndingCondition;
    pub use self::dream_maker_ending_reward_type_generated::DreamMakerEndingRewardType;
    pub use self::dream_maker_ending_type_generated::DreamMakerEndingType;
    pub use self::dream_maker_multiplier_condition_generated::DreamMakerMultiplierCondition;
    pub use self::dream_maker_param_operation_type_generated::DreamMakerParamOperationType;
    pub use self::dream_maker_parameter_type_generated::DreamMakerParameterType;
    pub use self::dream_maker_result_generated::DreamMakerResult;
    pub use self::echelon_extension_type_generated::EchelonExtensionType;
    pub use self::echelon_type_generated::EchelonType;
    pub use self::emoji_event_generated::EmojiEvent;
    pub use self::equipment_option_type_generated::EquipmentOptionType;
    pub use self::event_content_notify_excel_generated::EventContentNotifyExcel;
    pub use self::event_content_spoiler_popup_excel_generated::EventContentSpoilerPopupExcel;
    pub use self::event_content_treasure_cell_reward_excel_generated::EventContentTreasureCellRewardExcel;
    pub use self::event_content_treasure_excel_generated::EventContentTreasureExcel;
    pub use self::event_content_treasure_reward_excel_generated::EventContentTreasureRewardExcel;
    pub use self::event_content_treasure_round_excel_generated::EventContentTreasureRoundExcel;
    pub use self::event_content_type_generated::EventContentType;
    pub use self::event_notify_type_generated::EventNotifyType;
    pub use self::event_target_type_generated::EventTargetType;
    pub use self::farming_dungeon_location_manage_excel_generated::FarmingDungeonLocationManageExcel;
    pub use self::favor_level_excel_generated::FavorLevelExcel;
    pub use self::favor_level_reward_excel_generated::FavorLevelRewardExcel;
    pub use self::fixed_echelon_setting_excel_generated::FixedEchelonSettingExcel;
    pub use self::formation_location_excel_generated::FormationLocationExcel;
    pub use self::get_sticker_condition_type_generated::GetStickerConditionType;
    pub use self::ground_module_reward_excel_generated::GroundModuleRewardExcel;
    pub use self::id_card_background_excel_generated::IdCardBackgroundExcel;
    pub use self::information_excel_generated::InformationExcel;
    pub use self::loading_image_excel_generated::LoadingImageExcel;
    pub use self::localize_char_profile_change_excel_generated::LocalizeCharProfileChangeExcel;
    pub use self::localize_error_excel_generated::LocalizeErrorExcel;
    pub use self::localize_etc_excel_generated::LocalizeEtcExcel;
    pub use self::localize_excel_generated::LocalizeExcel;
    pub use self::localize_skill_excel_generated::LocalizeSkillExcel;
    pub use self::mail_type_generated::MailType;
    pub use self::memory_lobby_category_generated::MemoryLobbyCategory;
    pub use self::memory_lobby_excel_generated::MemoryLobbyExcel;
    pub use self::memory_lobby_global_excel_generated::MemoryLobby_GlobalExcel;
    pub use self::message_popup_button_type_generated::MessagePopupButtonType;
    pub use self::message_popup_excel_generated::MessagePopupExcel;
    pub use self::message_popup_image_position_type_generated::MessagePopupImagePositionType;
    pub use self::message_popup_layout_generated::MessagePopupLayout;
    pub use self::mini_game_defense_character_ban_excel_generated::MiniGameDefenseCharacterBanExcel;
    pub use self::mini_game_defense_fixed_stat_excel_generated::MiniGameDefenseFixedStatExcel;
    pub use self::mini_game_defense_info_excel_generated::MiniGameDefenseInfoExcel;
    pub use self::mini_game_defense_stage_excel_generated::MiniGameDefenseStageExcel;
    pub use self::mini_game_dream_collection_scenario_excel_generated::MiniGameDreamCollectionScenarioExcel;
    pub use self::mini_game_dream_daily_point_excel_generated::MiniGameDreamDailyPointExcel;
    pub use self::mini_game_dream_ending_excel_generated::MiniGameDreamEndingExcel;
    pub use self::mini_game_dream_ending_reward_excel_generated::MiniGameDreamEndingRewardExcel;
    pub use self::mini_game_dream_info_excel_generated::MiniGameDreamInfoExcel;
    pub use self::mini_game_dream_parameter_excel_generated::MiniGameDreamParameterExcel;
    pub use self::mini_game_dream_replay_scenario_excel_generated::MiniGameDreamReplayScenarioExcel;
    pub use self::mini_game_dream_schedule_excel_generated::MiniGameDreamScheduleExcel;
    pub use self::mini_game_dream_schedule_result_excel_generated::MiniGameDreamScheduleResultExcel;
    pub use self::mini_game_dream_timeline_excel_generated::MiniGameDreamTimelineExcel;
    pub use self::mini_game_road_puzzle_info_excel_generated::MiniGameRoadPuzzleInfoExcel;
    pub use self::mini_game_road_puzzle_map_excel_generated::MiniGameRoadPuzzleMapExcel;
    pub use self::mini_game_road_puzzle_rail_set_reward_excel_generated::MiniGameRoadPuzzleRailSetRewardExcel;
    pub use self::mini_game_road_puzzle_reward_excel_generated::MiniGameRoadPuzzleRewardExcel;
    pub use self::mini_game_road_puzzle_voice_excel_generated::MiniGameRoadPuzzleVoiceExcel;
    pub use self::mission_emergency_complete_excel_generated::MissionEmergencyCompleteExcel;
    pub use self::motion_generated::Motion;
    pub use self::move_end_generated::MoveEnd;
    pub use self::multi_floor_raid_reward_excel_generated::MultiFloorRaidRewardExcel;
    pub use self::multi_floor_raid_season_manage_excel_generated::MultiFloorRaidSeasonManageExcel;
    pub use self::multi_floor_raid_stage_excel_generated::MultiFloorRaidStageExcel;
    pub use self::multi_floor_raid_stat_change_excel_generated::MultiFloorRaidStatChangeExcel;
    pub use self::multiple_condition_check_type_generated::MultipleConditionCheckType;
    pub use self::nation_generated::Nation;
    pub use self::obstacle_stat_excel_generated::ObstacleStatExcel;
    pub use self::open_condition_content_generated::OpenConditionContent;
    pub use self::open_condition_excel_generated::OpenConditionExcel;
    pub use self::operator_condition_generated::OperatorCondition;
    pub use self::operator_excel_generated::OperatorExcel;
    pub use self::parcel_type_generated::ParcelType;
    pub use self::position_generated::{Position, PositionT};
    pub use self::potential_stat_bonus_rate_type_generated::PotentialStatBonusRateType;
    pub use self::production_step_generated::ProductionStep;
    pub use self::rarity_generated::Rarity;
    pub use self::reward_tag_generated::RewardTag;
    pub use self::road_puzzle_voice_condition_generated::RoadPuzzleVoiceCondition;
    pub use self::scenario_bgeffect_excel_generated::ScenarioBGEffectExcel;
    pub use self::scenario_bgname_excel_generated::ScenarioBGNameExcel;
    pub use self::scenario_bgname_global_excel_generated::ScenarioBGName_GlobalExcel;
    pub use self::scenario_bgscroll_generated::ScenarioBGScroll;
    pub use self::scenario_bgtype_generated::ScenarioBGType;
    pub use self::scenario_character_emotion_excel_generated::ScenarioCharacterEmotionExcel;
    pub use self::scenario_character_name_excel_generated::ScenarioCharacterNameExcel;
    pub use self::scenario_character_shapes_generated::ScenarioCharacterShapes;
    pub use self::scenario_character_situation_set_excel_generated::ScenarioCharacterSituationSetExcel;
    pub use self::scenario_content_collection_excel_generated::ScenarioContentCollectionExcel;
    pub use self::scenario_content_type_generated::ScenarioContentType;
    pub use self::scenario_effect_excel_generated::ScenarioEffectExcel;
    pub use self::scenario_mode_excel_generated::ScenarioModeExcel;
    pub use self::scenario_mode_reward_excel_generated::ScenarioModeRewardExcel;
    pub use self::scenario_mode_sub_types_generated::ScenarioModeSubTypes;
    pub use self::scenario_mode_types_generated::ScenarioModeTypes;
    pub use self::scenario_resource_info_excel_generated::ScenarioResourceInfoExcel;
    pub use self::scenario_script_excel_generated::ScenarioScriptExcel;
    pub use self::scenario_transition_excel_generated::ScenarioTransitionExcel;
    pub use self::school_dungeon_reward_excel_generated::SchoolDungeonRewardExcel;
    pub use self::school_dungeon_stage_excel_generated::SchoolDungeonStageExcel;
    pub use self::school_dungeon_type_generated::SchoolDungeonType;
    pub use self::service_action_excel_generated::ServiceActionExcel;
    pub use self::service_action_type_generated::ServiceActionType;
    pub use self::shortcut_content_type_generated::ShortcutContentType;
    pub use self::shortcut_type_excel_generated::ShortcutTypeExcel;
    pub use self::skill_additional_tooltip_excel_generated::SkillAdditionalTooltipExcel;
    pub use self::sound_uiexcel_generated::SoundUIExcel;
    pub use self::spine_lipsync_excel_generated::SpineLipsyncExcel;
    pub use self::stage_difficulty_generated::StageDifficulty;
    pub use self::stage_file_refresh_setting_excel_generated::StageFileRefreshSettingExcel;
    pub use self::stage_topography_generated::StageTopography;
    pub use self::star_goal_type_generated::StarGoalType;
    pub use self::stat_level_interpolation_excel_generated::StatLevelInterpolationExcel;
    pub use self::stat_level_up_type_generated::StatLevelUpType;
    pub use self::stat_type_generated::StatType;
    pub use self::sticker_check_pass_type_generated::StickerCheckPassType;
    pub use self::sticker_get_condition_type_generated::StickerGetConditionType;
    pub use self::sticker_group_excel_generated::StickerGroupExcel;
    pub use self::sticker_page_content_excel_generated::StickerPageContentExcel;
    pub use self::story_strategy_excel_generated::StoryStrategyExcel;
    pub use self::strategy_environment_generated::StrategyEnvironment;
    pub use self::tag_generated::Tag;
    pub use self::toast_excel_generated::ToastExcel;
    pub use self::toast_type_generated::ToastType;
    pub use self::tutorial_character_dialog_excel_generated::TutorialCharacterDialogExcel;
    pub use self::tutorial_excel_generated::TutorialExcel;
    pub use self::tutorial_failure_content_type_generated::TutorialFailureContentType;
    pub use self::tutorial_failure_image_excel_generated::TutorialFailureImageExcel;
    pub use self::under_cover_stage_excel_generated::UnderCoverStageExcel;
    pub use self::video_excel_generated::VideoExcel;
    pub use self::video_global_excel_generated::Video_GlobalExcel;
    pub use self::voice_common_excel_generated::VoiceCommonExcel;
    pub use self::voice_event_generated::VoiceEvent;
    pub use self::voice_excel_generated::VoiceExcel;
    pub use self::voice_logic_effect_excel_generated::VoiceLogicEffectExcel;
    pub use self::voice_room_exception_excel_generated::VoiceRoomExceptionExcel;
    pub use self::voice_spine_excel_generated::VoiceSpineExcel;
    pub use self::voice_timeline_excel_generated::VoiceTimelineExcel;
    pub use self::web_apierror_level_generated::WebAPIErrorLevel;
    pub use self::week_day_generated::WeekDay;
    pub use self::week_dungeon_type_generated::WeekDungeonType;
    pub use self::world_raid_condition_excel_generated::WorldRaidConditionExcel;
}
