// automatically generated by the FlatBuffers compiler, do not modify

// @generated
#[allow(unused_imports)]
use core::cmp::Ordering;
#[allow(unused_imports)]
use core::mem;
extern crate flatbuffers;
#[allow(unused_imports)]
use self::flatbuffers::{EndianScalar, Follow};

#[allow(dead_code)]
pub enum LocalizedMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LocalizedMessage<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LocalizedMessage<'a> {
    type Inner = LocalizedMessage<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

#[allow(dead_code)]
impl<'a> LocalizedMessage<'a> {
    pub const VT_MESSAGE_ID: flatbuffers::VOffsetT = 4;
    pub const VT_KOREAN: flatbuffers::VOffsetT = 6;
    pub const VT_JAPANESE: flatbuffers::VOffsetT = 8;
    pub const VT_THAI: flatbuffers::VOffsetT = 10;
    pub const VT_CHINESE: flatbuffers::VOffsetT = 12;
    pub const VT_ENGLISH: flatbuffers::VOffsetT = 14;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        LocalizedMessage { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args LocalizedMessageArgs<'args>,
    ) -> flatbuffers::WIPOffset<LocalizedMessage<'bldr>> {
        let mut builder = LocalizedMessageBuilder::new(_fbb);
        if let Some(x) = args.english {
            builder.add_english(x);
        }
        if let Some(x) = args.chinese {
            builder.add_chinese(x);
        }
        if let Some(x) = args.thai {
            builder.add_thai(x);
        }
        if let Some(x) = args.japanese {
            builder.add_japanese(x);
        }
        if let Some(x) = args.korean {
            builder.add_korean(x);
        }
        builder.add_message_id(args.message_id);
        builder.finish()
    }

    #[inline]
    pub fn message_id(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u32>(LocalizedMessage::VT_MESSAGE_ID, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn korean(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(LocalizedMessage::VT_KOREAN, None)
        }
    }
    #[inline]
    pub fn japanese(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(LocalizedMessage::VT_JAPANESE, None)
        }
    }
    #[inline]
    pub fn thai(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(LocalizedMessage::VT_THAI, None)
        }
    }
    #[inline]
    pub fn chinese(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(LocalizedMessage::VT_CHINESE, None)
        }
    }
    #[inline]
    pub fn english(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(LocalizedMessage::VT_ENGLISH, None)
        }
    }
}

impl flatbuffers::Verifiable for LocalizedMessage<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        #[allow(unused_imports)]
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<u32>("message_id", Self::VT_MESSAGE_ID, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("korean", Self::VT_KOREAN, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "japanese",
                Self::VT_JAPANESE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("thai", Self::VT_THAI, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("chinese", Self::VT_CHINESE, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("english", Self::VT_ENGLISH, false)?
            .finish();
        Ok(())
    }
}
pub struct LocalizedMessageArgs<'a> {
    pub message_id: u32,
    pub korean: Option<flatbuffers::WIPOffset<&'a str>>,
    pub japanese: Option<flatbuffers::WIPOffset<&'a str>>,
    pub thai: Option<flatbuffers::WIPOffset<&'a str>>,
    pub chinese: Option<flatbuffers::WIPOffset<&'a str>>,
    pub english: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for LocalizedMessageArgs<'a> {
    #[inline]
    fn default() -> Self {
        LocalizedMessageArgs {
            message_id: 0,
            korean: None,
            japanese: None,
            thai: None,
            chinese: None,
            english: None,
        }
    }
}

pub struct LocalizedMessageBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LocalizedMessageBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_message_id(&mut self, message_id: u32) {
        self.fbb_
            .push_slot::<u32>(LocalizedMessage::VT_MESSAGE_ID, message_id, 0);
    }
    #[inline]
    pub fn add_korean(&mut self, korean: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(LocalizedMessage::VT_KOREAN, korean);
    }
    #[inline]
    pub fn add_japanese(&mut self, japanese: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(LocalizedMessage::VT_JAPANESE, japanese);
    }
    #[inline]
    pub fn add_thai(&mut self, thai: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(LocalizedMessage::VT_THAI, thai);
    }
    #[inline]
    pub fn add_chinese(&mut self, chinese: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(LocalizedMessage::VT_CHINESE, chinese);
    }
    #[inline]
    pub fn add_english(&mut self, english: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(LocalizedMessage::VT_ENGLISH, english);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> LocalizedMessageBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        LocalizedMessageBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<LocalizedMessage<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for LocalizedMessage<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("LocalizedMessage");
        ds.field("message_id", &self.message_id());
        ds.field("korean", &self.korean());
        ds.field("japanese", &self.japanese());
        ds.field("thai", &self.thai());
        ds.field("chinese", &self.chinese());
        ds.field("english", &self.english());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `LocalizedMessage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_localized_message_unchecked`.
#[allow(mismatched_lifetime_syntaxes)]
pub fn root_as_localized_message(
    buf: &[u8],
) -> Result<LocalizedMessage, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<LocalizedMessage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `LocalizedMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_localized_message_unchecked`.
#[allow(mismatched_lifetime_syntaxes)]
#[allow(dead_code)]
pub fn size_prefixed_root_as_localized_message(
    buf: &[u8],
) -> Result<LocalizedMessage, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<LocalizedMessage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `LocalizedMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_localized_message_unchecked`.
#[allow(dead_code)]
pub fn root_as_localized_message_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<LocalizedMessage<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<LocalizedMessage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `LocalizedMessage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_localized_message_unchecked`.
#[allow(dead_code)]
pub fn size_prefixed_root_as_localized_message_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<LocalizedMessage<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<LocalizedMessage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a LocalizedMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `LocalizedMessage`.
#[allow(dead_code)]
#[allow(mismatched_lifetime_syntaxes)]
pub unsafe fn root_as_localized_message_unchecked(buf: &[u8]) -> LocalizedMessage {
    unsafe { flatbuffers::root_unchecked::<LocalizedMessage>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed LocalizedMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `LocalizedMessage`.
#[allow(dead_code)]
#[allow(mismatched_lifetime_syntaxes)]
pub unsafe fn size_prefixed_root_as_localized_message_unchecked(buf: &[u8]) -> LocalizedMessage {
    unsafe { flatbuffers::size_prefixed_root_unchecked::<LocalizedMessage>(buf) }
}
#[allow(dead_code)]
pub const LOCALIZED_MESSAGE_IDENTIFIER: &str = "LMSG";

#[inline]
#[allow(dead_code)]
pub fn localized_message_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, LOCALIZED_MESSAGE_IDENTIFIER, false)
}

#[inline]
#[allow(dead_code)]
pub fn localized_message_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, LOCALIZED_MESSAGE_IDENTIFIER, true)
}

#[inline]
#[allow(dead_code)]
pub fn finish_localized_message_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<LocalizedMessage<'a>>,
) {
    fbb.finish(root, Some(LOCALIZED_MESSAGE_IDENTIFIER));
}

#[inline]
#[allow(dead_code)]
pub fn finish_size_prefixed_localized_message_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<LocalizedMessage<'a>>,
) {
    fbb.finish_size_prefixed(root, Some(LOCALIZED_MESSAGE_IDENTIFIER));
}
